/**
 * Guided decision engine for the MesaHomes platform.
 *
 * Walks visitors through a persona-specific sequence of tools, tracks
 * progress, and generates contextual "What's Next" recommendations.
 */

import type { GuidedPath } from '../types/scenario.js';
import { GUIDED_PATHS, type PathStep } from './paths.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Progress snapshot for a guided path. */
export interface PathProgressInfo {
  /** The next step the visitor should complete (null if path is done). */
  currentStep: PathStep | null;
  /** Steps already completed, in path order. */
  completedSteps: PathStep[];
  /** Steps not yet completed, in path order. */
  remainingSteps: PathStep[];
  /** Completion percentage (0–100, integer). */
  percentComplete: number;
}

/** WhatsNextCard content generated by the engine. */
export interface WhatsNextMessage {
  /** Card title — the next tool name. */
  title: string;
  /** Why this step matters, optionally personalized with tool results. */
  explanation: string;
  /** Link to the next tool page. */
  href: string;
}

// ---------------------------------------------------------------------------
// Engine functions
// ---------------------------------------------------------------------------

/**
 * Return the next step in the path that hasn't been completed yet.
 * Returns `null` when every step in the path is done.
 */
export function getNextStep(
  pathType: GuidedPath,
  completedStepIds: string[],
): PathStep | null {
  const steps = GUIDED_PATHS[pathType];
  const completedSet = new Set(completedStepIds);

  for (const step of steps) {
    if (!completedSet.has(step.id)) {
      return step;
    }
  }

  return null;
}

/**
 * Build a full progress snapshot for the given path and completed steps.
 */
export function getPathProgress(
  pathType: GuidedPath,
  completedStepIds: string[],
): PathProgressInfo {
  const steps = GUIDED_PATHS[pathType];
  const completedSet = new Set(completedStepIds);

  const completedSteps: PathStep[] = [];
  const remainingSteps: PathStep[] = [];

  for (const step of steps) {
    if (completedSet.has(step.id)) {
      completedSteps.push(step);
    } else {
      remainingSteps.push(step);
    }
  }

  const total = steps.length;
  const percentComplete = total === 0 ? 100 : Math.round((completedSteps.length / total) * 100);
  const currentStep = remainingSteps.length > 0 ? remainingSteps[0] : null;

  return {
    currentStep,
    completedSteps,
    remainingSteps,
    percentComplete,
  };
}

/**
 * Generate a WhatsNextCard message for the current position in the path.
 *
 * If `toolResults` are provided, the explanation can be personalized
 * (e.g. referencing the visitor's estimated home value). Falls back to
 * the step's default description when no results are available.
 *
 * Returns `null` when the path is complete.
 */
export function generateWhatsNextMessage(
  pathType: GuidedPath,
  currentStepId: string,
  toolResults?: Record<string, unknown>,
): WhatsNextMessage | null {
  const steps = GUIDED_PATHS[pathType];
  const currentIndex = steps.findIndex((s) => s.id === currentStepId);

  if (currentIndex === -1) return null;

  // The "next" step is the one after the current step
  const nextStep = steps[currentIndex + 1];
  if (!nextStep) return null;

  // Personalize explanation when tool results are available
  let explanation = nextStep.description;

  if (toolResults) {
    explanation = personalizeExplanation(nextStep.id, nextStep.description, toolResults);
  }

  return {
    title: nextStep.label,
    explanation,
    href: nextStep.href,
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Attempt to personalize a step explanation using tool results.
 * Returns the original description if no personalization applies.
 */
function personalizeExplanation(
  stepId: string,
  defaultDescription: string,
  toolResults: Record<string, unknown>,
): string {
  const homeValue = toolResults['estimatedValue'] as number | undefined;
  const monthlyPayment = toolResults['monthlyPayment'] as number | undefined;
  const netProceeds = toolResults['netProceeds'] as number | undefined;

  switch (stepId) {
    case 'net-sheet':
      if (homeValue) {
        return `Your home is estimated at $${homeValue.toLocaleString()}. Now let's calculate your net proceeds after all costs.`;
      }
      break;
    case 'sell-now-or-wait':
      if (netProceeds) {
        return `You'd net about $${netProceeds.toLocaleString()}. Let's see if waiting could improve that number.`;
      }
      break;
    case 'first-time-guide':
      if (monthlyPayment) {
        return `At $${monthlyPayment.toLocaleString()}/mo, you're in good shape. Let's walk through the buying process.`;
      }
      break;
    default:
      break;
  }

  return defaultDescription;
}
